create type "public"."FriendshipStatus" as enum ('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED');

create table "public"."Friendship" (
    "user_id1" uuid not null default gen_random_uuid(),
    "user_id2" uuid not null default gen_random_uuid(),
    "friendship_status" "FriendshipStatus" not null,
    "created_at" timestamp without time zone not null default now()
);


alter table "public"."Friendship" enable row level security;

create table "public"."Notification" (
    "notification_id" bigint generated by default as identity not null,
    "user_id" uuid not null default gen_random_uuid(),
    "message" text,
    "is_read" boolean not null default false,
    "created_at" timestamp without time zone not null default now()
);


alter table "public"."Notification" enable row level security;

create table "public"."Review" (
    "review_id" bigint generated by default as identity not null,
    "user_id" uuid not null default gen_random_uuid(),
    "venue_id" uuid default gen_random_uuid(),
    "overall_rating" bigint,
    "ambiance_rating" bigint,
    "music_rating" bigint,
    "crowd_rating" bigint,
    "service_rating" bigint,
    "review_text" text,
    "created_at" timestamp without time zone not null default now(),
    "udpated_at" timestamp without time zone
);


alter table "public"."Review" enable row level security;

create table "public"."SearchHistory" (
    "search_id" bigint generated by default as identity not null,
    "user_id" uuid default gen_random_uuid(),
    "search_term" timestamp without time zone not null,
    "search_time" timestamp without time zone not null default now()
);


alter table "public"."SearchHistory" enable row level security;

CREATE UNIQUE INDEX "Friendship_pkey" ON public."Friendship" USING btree (user_id1, user_id2);

CREATE UNIQUE INDEX "Notification_notification_id_key" ON public."Notification" USING btree (notification_id);

CREATE UNIQUE INDEX "Notification_pkey" ON public."Notification" USING btree (notification_id);

CREATE UNIQUE INDEX "Review_pkey" ON public."Review" USING btree (review_id);

CREATE UNIQUE INDEX "Review_review_id_key" ON public."Review" USING btree (review_id);

CREATE UNIQUE INDEX "SearchHistory_pkey" ON public."SearchHistory" USING btree (search_id);

CREATE UNIQUE INDEX "SearchHistory_search_id_key" ON public."SearchHistory" USING btree (search_id);

alter table "public"."Friendship" add constraint "Friendship_pkey" PRIMARY KEY using index "Friendship_pkey";

alter table "public"."Notification" add constraint "Notification_pkey" PRIMARY KEY using index "Notification_pkey";

alter table "public"."Review" add constraint "Review_pkey" PRIMARY KEY using index "Review_pkey";

alter table "public"."SearchHistory" add constraint "SearchHistory_pkey" PRIMARY KEY using index "SearchHistory_pkey";

alter table "public"."Friendship" add constraint "Friendship_user_id1_fkey" FOREIGN KEY (user_id1) REFERENCES "User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Friendship" validate constraint "Friendship_user_id1_fkey";

alter table "public"."Friendship" add constraint "Friendship_user_id2_fkey" FOREIGN KEY (user_id2) REFERENCES "User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Friendship" validate constraint "Friendship_user_id2_fkey";

alter table "public"."Notification" add constraint "Notification_notification_id_key" UNIQUE using index "Notification_notification_id_key";

alter table "public"."Notification" add constraint "Notification_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Notification" validate constraint "Notification_user_id_fkey";

alter table "public"."Review" add constraint "Review_ambiance_rating_check" CHECK (((ambiance_rating >= 1) AND (ambiance_rating <= 10))) not valid;

alter table "public"."Review" validate constraint "Review_ambiance_rating_check";

alter table "public"."Review" add constraint "Review_crowd_rating_check" CHECK (((crowd_rating >= 1) AND (crowd_rating <= 10))) not valid;

alter table "public"."Review" validate constraint "Review_crowd_rating_check";

alter table "public"."Review" add constraint "Review_music_rating_check" CHECK (((music_rating >= 1) AND (music_rating <= 10))) not valid;

alter table "public"."Review" validate constraint "Review_music_rating_check";

alter table "public"."Review" add constraint "Review_overall_rating_check" CHECK (((overall_rating >= 1) AND (overall_rating <= 5))) not valid;

alter table "public"."Review" validate constraint "Review_overall_rating_check";

alter table "public"."Review" add constraint "Review_review_id_key" UNIQUE using index "Review_review_id_key";

alter table "public"."Review" add constraint "Review_service_rating_check" CHECK (((service_rating >= 1) AND (service_rating <= 10))) not valid;

alter table "public"."Review" validate constraint "Review_service_rating_check";

alter table "public"."Review" add constraint "Review_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Review" validate constraint "Review_user_id_fkey";

alter table "public"."Review" add constraint "Review_venue_id_fkey" FOREIGN KEY (venue_id) REFERENCES "Venue"(venue_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Review" validate constraint "Review_venue_id_fkey";

alter table "public"."SearchHistory" add constraint "SearchHistory_search_id_key" UNIQUE using index "SearchHistory_search_id_key";

alter table "public"."SearchHistory" add constraint "SearchHistory_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "User"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."SearchHistory" validate constraint "SearchHistory_user_id_fkey";

grant delete on table "public"."Friendship" to "anon";

grant insert on table "public"."Friendship" to "anon";

grant references on table "public"."Friendship" to "anon";

grant select on table "public"."Friendship" to "anon";

grant trigger on table "public"."Friendship" to "anon";

grant truncate on table "public"."Friendship" to "anon";

grant update on table "public"."Friendship" to "anon";

grant delete on table "public"."Friendship" to "authenticated";

grant insert on table "public"."Friendship" to "authenticated";

grant references on table "public"."Friendship" to "authenticated";

grant select on table "public"."Friendship" to "authenticated";

grant trigger on table "public"."Friendship" to "authenticated";

grant truncate on table "public"."Friendship" to "authenticated";

grant update on table "public"."Friendship" to "authenticated";

grant delete on table "public"."Friendship" to "service_role";

grant insert on table "public"."Friendship" to "service_role";

grant references on table "public"."Friendship" to "service_role";

grant select on table "public"."Friendship" to "service_role";

grant trigger on table "public"."Friendship" to "service_role";

grant truncate on table "public"."Friendship" to "service_role";

grant update on table "public"."Friendship" to "service_role";

grant delete on table "public"."Notification" to "anon";

grant insert on table "public"."Notification" to "anon";

grant references on table "public"."Notification" to "anon";

grant select on table "public"."Notification" to "anon";

grant trigger on table "public"."Notification" to "anon";

grant truncate on table "public"."Notification" to "anon";

grant update on table "public"."Notification" to "anon";

grant delete on table "public"."Notification" to "authenticated";

grant insert on table "public"."Notification" to "authenticated";

grant references on table "public"."Notification" to "authenticated";

grant select on table "public"."Notification" to "authenticated";

grant trigger on table "public"."Notification" to "authenticated";

grant truncate on table "public"."Notification" to "authenticated";

grant update on table "public"."Notification" to "authenticated";

grant delete on table "public"."Notification" to "service_role";

grant insert on table "public"."Notification" to "service_role";

grant references on table "public"."Notification" to "service_role";

grant select on table "public"."Notification" to "service_role";

grant trigger on table "public"."Notification" to "service_role";

grant truncate on table "public"."Notification" to "service_role";

grant update on table "public"."Notification" to "service_role";

grant delete on table "public"."Review" to "anon";

grant insert on table "public"."Review" to "anon";

grant references on table "public"."Review" to "anon";

grant select on table "public"."Review" to "anon";

grant trigger on table "public"."Review" to "anon";

grant truncate on table "public"."Review" to "anon";

grant update on table "public"."Review" to "anon";

grant delete on table "public"."Review" to "authenticated";

grant insert on table "public"."Review" to "authenticated";

grant references on table "public"."Review" to "authenticated";

grant select on table "public"."Review" to "authenticated";

grant trigger on table "public"."Review" to "authenticated";

grant truncate on table "public"."Review" to "authenticated";

grant update on table "public"."Review" to "authenticated";

grant delete on table "public"."Review" to "service_role";

grant insert on table "public"."Review" to "service_role";

grant references on table "public"."Review" to "service_role";

grant select on table "public"."Review" to "service_role";

grant trigger on table "public"."Review" to "service_role";

grant truncate on table "public"."Review" to "service_role";

grant update on table "public"."Review" to "service_role";

grant delete on table "public"."SearchHistory" to "anon";

grant insert on table "public"."SearchHistory" to "anon";

grant references on table "public"."SearchHistory" to "anon";

grant select on table "public"."SearchHistory" to "anon";

grant trigger on table "public"."SearchHistory" to "anon";

grant truncate on table "public"."SearchHistory" to "anon";

grant update on table "public"."SearchHistory" to "anon";

grant delete on table "public"."SearchHistory" to "authenticated";

grant insert on table "public"."SearchHistory" to "authenticated";

grant references on table "public"."SearchHistory" to "authenticated";

grant select on table "public"."SearchHistory" to "authenticated";

grant trigger on table "public"."SearchHistory" to "authenticated";

grant truncate on table "public"."SearchHistory" to "authenticated";

grant update on table "public"."SearchHistory" to "authenticated";

grant delete on table "public"."SearchHistory" to "service_role";

grant insert on table "public"."SearchHistory" to "service_role";

grant references on table "public"."SearchHistory" to "service_role";

grant select on table "public"."SearchHistory" to "service_role";

grant trigger on table "public"."SearchHistory" to "service_role";

grant truncate on table "public"."SearchHistory" to "service_role";

grant update on table "public"."SearchHistory" to "service_role";


