name: CI

on:
  pull_request:
    branches:
      - main

jobs:

  ci-config:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: List files in working dir
          run: ls -al



  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: make frontend-dep
      - name: Run frontend linter
        run: make frontend-lint

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install backend dependencies
        run: make backend-dep
      - name: Run backend linter
        run: make backend-lint
      - name: Run frontend linter
        run: make frontend-lint
      

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: make frontend-dep
      - name: Build database
        run: make db-run
      - name: Run backend build
        run: make backend-run
