name: CI

on:
  pull_request:
    branches:
      - main

jobs:

  ci-config:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: List files in working dir
          run: ls -al



  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: make frontend-dep
      - name: Run frontend linter
        run: make frontend-lint

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install backend dependencies
        run: make backend-dep
      - name: Run backend linter
        run: make backend-lint
      

  backend-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run all backend tests
        run: make backend-test
